export const countryCodes = [
    { name: "China", code: "+86" },
    { name: "India", code: "+91" },
    { name: "Estados Unidos", code: "+1" },
    { name: "Indonesia", code: "+62" },
    { name: "Brasil", code: "+55" },
    { name: "Rusia", code: "+7" },
    { name: "Japón", code: "+81" },
    { name: "México", code: "+52" },
    { name: "Vietnam", code: "+84" },
    { name: "Alemania", code: "+49" },
    { name: "Filipinas", code: "+63" },
    { name: "Nigeria", code: "+234" },
    { name: "Turquía", code: "+90" },
    { name: "Reino Unido", code: "+44" },
    { name: "Francia", code: "+33" },
    { name: "Tailandia", code: "+66" },
    { name: "Italia", code: "+39" },
    { name: "Egipto", code: "+20" },
    { name: "Bangladés", code: "+880" },
    { name: "Pakistán", code: "+92" },
    { name: "Irán", code: "+98" },
    { name: "Corea del Sur", code: "+82" },
    { name: "Argentina", code: "+54" },
    { name: "Sudáfrica", code: "+27" },
    { name: "Ucrania", code: "+380" },
    { name: "España", code: "+34" },
    { name: "Colombia", code: "+57" },
    { name: "Polonia", code: "+48" },
    { name: "Malasia", code: "+60" },
    { name: "Arabia Saudita", code: "+966" },
    { name: "Uzbekistán", code: "+998" },
    { name: "Perú", code: "+51" },
    { name: "Venezuela", code: "+58" },
    { name: "Chile", code: "+56" },
    { name: "Australia", code: "+61" },
    { name: "Rumania", code: "+40" },
    { name: "Países Bajos", code: "+31" },
    { name: "Nepal", code: "+977" },
    { name: "Afganistán", code: "+93" },
    { name: "Ghana", code: "+233" },
    { name: "Mozambique", code: "+258" },
    { name: "Yemen", code: "+967" },
    { name: "Corea del Norte", code: "+850" },
    { name: "Taiwán", code: "+886" },
    { name: "Sri Lanka", code: "+94" },
    { name: "Camerún", code: "+237" },
    { name: "Angola", code: "+244" },
  ];