export const mockProducts = [
    {
      id: 1,
      name: "Accesorio para amortiguador SlideOn e Intermat",
      brand: "Hettich",
      price: 1599.99,
      img1: "/img/Cajafuerte.png",
      img2: "/img/Cajafuerte2.jpg",
      available: true,
      isNew: true,
    },
    {
      id: 2,
      name: "Aldabilla 3",
      brand: "Amig",
      price: 499.99,
      img1: "/img/Cajafuerte.png",
      img2: "/img/Cajafuerte2.jpg",
      available: true,
      isNew: false,
    },
    {
      id: 3,
      name: "Aldabilla 3 Black",
      brand: "Amig",
      price: 799.99,
      img1: "/img/Cajafuerte.png",
      img2: "/img/Cajafuerte2.jpg",
      available: true,
      isNew: false,
    },
    {
        id: 1,
        name: "Accesorio para amortiguador SlideOn e Intermat",
        brand: "Hettich",
        price: 1599.99,
        img1: "/img/Cajafuerte.png",
        img2: "/img/Cajafuerte2.jpg",
        available: true,
        isNew: true,
      },
      {
        id: 2,
        name: "Aldabilla 3",
        brand: "Amig",
        price: 499.99,
        img1: "/img/Cajafuerte.png",
        img2: "/img/Cajafuerte2.jpg",
        available: true,
        isNew: false,
      },
      {
        id: 3,
        name: "Aldabilla 3 Black",
        brand: "Amig",
        price: 799.99,
        img1: "/img/Cajafuerte.png",
        img2: "/img/Cajafuerte2.jpg",
        available: true,
        isNew: false,
      },
      {
        id: 1,
        name: "Accesorio para amortiguador SlideOn e Intermat",
        brand: "Hettich",
        price: 1599.99,
        img1: "/img/Cajafuerte.png",
        img2: "/img/Cajafuerte2.jpg",
        available: true,
        isNew: true,
      },
      {
        id: 2,
        name: "Aldabilla 3",
        brand: "Amig",
        price: 499.99,
        img1: "/img/Cajafuerte.png",
        img2: "/img/Cajafuerte2.jpg",
        available: true,
        isNew: false,
      },
      {
        id: 3,
        name: "Aldabilla 3 Black",
        brand: "Amig",
        price: 799.99,
        img1: "/img/Cajafuerte.png",
        img2: "/img/Cajafuerte2.jpg",
        available: true,
        isNew: false,
      },
  ];
  

  export   const categories = [
    {
      name: "Productos para el Hogar",
      sub: [],
    },
    {
      name: "Uso Industrial",
      sub: [],
    },
    {
      name: "Cerrajería",
      sub: [],
    },
    {
      name: "Herrajes (103)",
      sub: [],
    },
    {
      name: "Línea Black Color (106)",
      sub: [
        "Bisagras",
        "Buzones y Bocacartas",
        "Candados",
        "Cajas de seguridad",
        "Cerraduras",
        "Digitales",
        "Jaladeras",
        "Pasador",
        "Perchero",
      ],
    },
  ];